version: '3.7'

networks:
  kong-net:
    external: false

services:
  kong:
    build:
      context: ./config/kong
      dockerfile: ./Dockerfile
    volumes:
      - ./config/kong/kong.yml:/usr/local/kong/declarative/kong.yml
      - ./plugins/builds:/usr/local/kong/go-plugins
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PLUGINS=go-powered-by,go-seminarios-address
      - KONG_PLUGINSERVER_NAMES=go-powered-by,go-seminarios-address
      - KONG_PLUGINSERVER_GO_POWERED_BY_QUERY_CMD=/usr/local/kong/go-plugins/go-powered-by -dump
      - KONG_PLUGINSERVER_GO_SEMINARIOS_ADDRESS_QUERY_CMD=/usr/local/kong/go-plugins/go-seminarios-address -dump
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "127.0.0.1:8443:8443"
      - "8001:8001"
      - "127.0.0.1:8444:8444"
#    restart: on-failure
    networks:
      - kong-net

  konga:
      image: pantsel/konga
      environment:
        NODE_ENV: ${KONGA_ENV:-production}
        KONGA_HOOK_TIMEOUT: 10000
      restart: on-failure
      ports:
        - ${KONGA_PORT:-9000}:1337
      depends_on:
        - kong
      links:
        - kong
      networks:
        - kong-net
      volumes:
        - ./config/konga.db:/app/kongadata/konga.db
