_format_version: "2.1"

services:
  - name: health-check
    url: http://host.docker.internal:3000
    routes:
      - name: health-check
        paths:
          - /status
    plugins:
      - name: go-powered-by
        config:
          poweredby: "EIC Kong"
      - name: go-seminaries-address
        config:
          seminariosaddress: "https://eic-seminarios.com"
  - name: authy
    url: http://host.docker.internal:3001
    routes:
      - name: authy
        paths:
          - /v1/authy
        plugins:
          - name: go-powered-by
            config:
              poweredby: "EIC Kong"
          - name: go-seminaries-address
            config:
              seminariosaddress: "https://eic-seminarios.com"